((python-mode . ((indent-tabs-mode . nil)
                 (tab-width . 4)
                 (fill-column . 80)))
 (web-mode . ((indent-tabs-mode . nil)
              (tab-width . 2)
              (web-mode-markup-indent-offset . 4)
              (web-mode-css-indent-offset . 4)
              (web-mode-code-indent-offset . 2)
              (web-mode-indent-style . 4)
              (web-mode-enable-auto-pairing . nil)
              (web-mode-enable-auto-quoting . nil)
              (fill-column . 80)))
 (sql-mode . ((indent-tabs-mode . nil)
              (tab-width . 4)
              (fill-column . 80))))
