((python-mode . ((indent-tabs-mode . nil)
                 (tab-width . 4)
                 (fill-column . 120)))
 (web-mode . ((indent-tabs-mode . nil)
              (tab-width . 4)
              (fill-column . 120)))
 (sql-mode . ((indent-tabs-mode . nil)
              (tab-width . 4)
              (fill-column . 120))))
